import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Rajkumar Dake | Software Engineer",
  description:
    "Portfolio of Rajkumar Dake, Software Engineer at InfoEdge India Ltd and B.Tech CSE graduate from NIT Jamshedpur, showcasing work on Agentic PropGPT, AI tools, and full-stack projects.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Rajkumar Dake",
    url: "mailto:rajkumardakey831@gmail.com",
  },
} as const;
